TRUNCATE TABLE logtransactions CASCADE;
TRUNCATE TABLE contracts CASCADE;
TRUNCATE TABLE vault CASCADE;
TRUNCATE TABLE vaultcategory CASCADE;
TRUNCATE TABLE asset CASCADE;
TRUNCATE TABLE key CASCADE;
TRUNCATE TABLE wallet CASCADE;
TRUNCATE TABLE useraccount CASCADE;

ALTER SEQUENCE public.key_id_seq RESTART 1;
ALTER SEQUENCE public.wallet_id_seq RESTART 1;
