export enum PathRoute {
  HOME = '/',
  LOGIN = '/login/:expired?',
  SIGNUP = '/signup',
  RESET_PASSWORD = '/reset-password',
  PAYMENT_TOKENS = '/payment-tokens',
  SECURITIES_TOKENS = '/securities-tokens',
  SOROBAN_SMART_CONTRACTS = '/soroban-smart-contracts',
  ASSETS_DASHBOARD = '/assets-dashboard',
  BLOCKCHAIN_EXPLORER = '/blockchain-explorer',
  SETTINGS = '/settings',
  PROFILE = '/profile',
  FORGE_ASSET = '/forge-asset',
  MINT_ASSET = '/asset-management/mint',
  BURN_ASSET = '/asset-management/burn',
  DISTRIBUTE_ASSET = '/asset-management/distribute',
  AUTHORIZE_ACCOUNT = '/asset-management/authorize',
  CLAWBACK_ASSET = '/asset-management/clawback',
  FREEZE_ACCOUNT = '/asset-management/freeze',
}
